### ISSUE TITLE
Not able to install it on go 1.7

### ISSUE THREAD

**Issue by tappoz** [scholzj/amqpctl#2]
I have compiled and installed `proton-c` 0.18.0 on a Linux Debian machine (I can see stuff related to `proton-c` in `/usr/lib`). I am using golang 1.7.

When attempting at getting it I see this:

```sh
$ go get github.com/scholzj/amqpctl
# github.com/scholzj/amqpctl/mgmtlink
<MY_GOPATH>/src/github.com/scholzj/amqpctl/mgmtlink/amqpmgmtlink.go:121: tlsConfig.GetClientCertificate undefined (type *tls.Config has no field or method GetClientCertificate)
<MY_GOPATH>/src/github.com/scholzj/amqpctl/mgmtlink/amqpmgmtlink.go:121: undefined: tls.CertificateRequestInfo
$
```

**Comment by scholzj** [comment]
This looks like it might be related to Go version and not Proton version. I never used it with 1.7. I used only with 1.8 and 1.9. `CertificateRequestInfo` and `GetClientCertificate` are new in [1.8](https://golang.org/doc/go1.8). 

Could you update Go to 1.8 or 1.9? I'm probably not going to change this to support also Go 1.7. Sorry.

**Comment by tappoz** [comment]
Yeah no worries I did not mean to ask for support for version 1.7, right now I can not update the version (on other machines I am usually on 1.8). Having a hook in the docs about the supported version helps :) Thanks
